spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Guodongxu@123
    url: jdbc:mysql://localhost:3306/memo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8

mybatis:
 configuration:
   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
 mapper-locations: classpath:/mapper/*.xml  # 指定MyBatis Mapper XML文件的位置
 #type-aliases-package: com.yourpackage.model  # 指定别名包路径      